"use strict";

const assert = require("node:assert/strict");
const { test } = require("node:test");
const fs = require("node:fs");
const path = require("node:path");
const { channelIdForLink, memberNoiseAttestBytes, verifyMemberNoiseAttestation } = require("./attestation.js");

// Real vectors generated by CADS-Tunnel's own Rust code (ct_common::channel's
// channel_id_for_link / member_noise_attest_bytes / verify_member_noise_attestation) -- not
// hand-derived. Regenerate via the throwaway Rust program described in this session's waiting-
// room plan if channel.rs's byte layout ever changes; a stale fixture here would pass against a
// stale JS port and prove nothing.
const vectors = JSON.parse(fs.readFileSync(path.join(__dirname, "testdata", "attestation-vectors.json"), "utf8"));
const hex = (h) => Buffer.from(h, "hex");

test("channelIdForLink matches the real Rust implementation", () => {
  const got = channelIdForLink(hex(vectors.operator_pub), hex(vectors.holder_a_pub), hex(vectors.holder_b_pub));
  assert.equal(got.toString("hex"), vectors.channel_id_for_link_a_b);
});

test("channelIdForLink is order-independent (both endpoints derive the same id)", () => {
  const a = channelIdForLink(hex(vectors.operator_pub), hex(vectors.holder_a_pub), hex(vectors.holder_b_pub));
  const b = channelIdForLink(hex(vectors.operator_pub), hex(vectors.holder_b_pub), hex(vectors.holder_a_pub));
  assert.equal(a.toString("hex"), b.toString("hex"));
});

test("memberNoiseAttestBytes produces the exact preimage bytes the Rust signer signed", () => {
  const got = memberNoiseAttestBytes(hex(vectors.channel_id_for_link_a_b), hex(vectors.holder_a_pub), hex(vectors.noise_a_pub));
  assert.equal(got.toString("hex"), vectors.attestation_preimage_hex);
});

test("verifyMemberNoiseAttestation: accepts a genuine attestation", () => {
  const c = vectors.positive;
  assert.equal(verifyMemberNoiseAttestation(hex(c.channel), hex(c.holder), hex(c.noise_pubkey), hex(c.signature)), true);
});

test("verifyMemberNoiseAttestation: rejects a signature checked against the wrong channel", () => {
  const c = vectors.negative_wrong_channel;
  assert.equal(verifyMemberNoiseAttestation(hex(c.channel), hex(c.holder), hex(c.noise_pubkey), hex(c.signature)), false);
});

test("verifyMemberNoiseAttestation: rejects a signature made by the wrong holder", () => {
  const c = vectors.negative_wrong_holder_signature;
  assert.equal(verifyMemberNoiseAttestation(hex(c.channel), hex(c.holder), hex(c.noise_pubkey), hex(c.signature)), false);
});

test("verifyMemberNoiseAttestation: rejects a genuine signature checked against a substituted noise key", () => {
  const c = vectors.negative_wrong_noise_key;
  assert.equal(verifyMemberNoiseAttestation(hex(c.channel), hex(c.holder), hex(c.noise_pubkey), hex(c.signature)), false);
});

test("verifyMemberNoiseAttestation: never throws on malformed input, just returns false", () => {
  assert.equal(verifyMemberNoiseAttestation(Buffer.from("short"), hex(vectors.holder_a_pub), hex(vectors.noise_a_pub), hex(vectors.positive.signature)), false);
  assert.equal(verifyMemberNoiseAttestation(hex(vectors.channel_id_for_link_a_b), Buffer.alloc(32, 0), hex(vectors.noise_a_pub), hex(vectors.positive.signature)), false);
  assert.equal(verifyMemberNoiseAttestation(hex(vectors.channel_id_for_link_a_b), hex(vectors.holder_a_pub), hex(vectors.noise_a_pub), Buffer.alloc(10)), false);
});
