"use strict";

/**
 * Sort Arena waiting room — channel-identity crypto, pure core.
 *
 * A byte-for-byte JS port of two functions from CADS-Tunnel's `crates/common/src/channel.rs`
 * (and the `Preimage` builder in `crates/common/src/preimage.rs` that backs one of them):
 * `channel_id_for_link` and `member_noise_attest_bytes`/`verify_member_noise_attestation`. The
 * bridge needs these to verify, server-side, that a participant who submits a join request
 * genuinely holds the holder private key for the pubkey they claim — without that check, the
 * waiting room would queue unverifiable garbage for an operator to discover only at approval
 * time.
 *
 * Verified against real vectors generated by the actual Rust code (not just re-derived from
 * reading the source) — see bridge/server.test.js's "attestation" describe block. If this file
 * and channel.rs ever disagree, channel.rs is the source of truth and this file is a bug.
 *
 * Process/network-free on purpose, same split as server.lib.js: this is pure crypto over
 * Buffers, no I/O, so it's directly unit-testable.
 */

const crypto = require("node:crypto");

// Ed25519 SubjectPublicKeyInfo DER prefix for a raw 32-byte public key (fixed, since Ed25519's
// SPKI structure has no variable-length fields ahead of the key itself) — lets node:crypto verify
// a raw key without a PEM/x509 round-trip. Confirmed against Node 20 (the bridge's own runtime).
const ED25519_SPKI_DER_PREFIX = Buffer.from("302a300506032b6570032100", "hex");

/** Preimage::new(domain).fixed(...).fixed(...)... — u32-LE length-prefixed domain, then fields
 *  appended verbatim (preimage.rs). Only fixed-width fields are used anywhere in this file, so
 *  no field itself needs a length prefix — only the leading domain does. */
function preimage(domain, ...fixedFields) {
  const domainBuf = Buffer.from(domain, "utf8");
  const lenPrefix = Buffer.alloc(4);
  lenPrefix.writeUInt32LE(domainBuf.length, 0);
  return Buffer.concat([lenPrefix, domainBuf, ...fixedFields]);
}

/** channel_id_for_link: SHA-256(domain ‖ operator_pubkey ‖ min(holderA,holderB) ‖
 *  max(holderA,holderB)) — order-independent so both endpoints derive the same id locally with
 *  no coordination round-trip. Not built via Preimage in the Rust source (a raw Sha256::update
 *  sequence instead) — matched here byte-for-byte regardless. Returns a 32-byte Buffer. */
function channelIdForLink(operatorPubkey, holderA, holderB) {
  const [lo, hi] = Buffer.compare(holderA, holderB) <= 0 ? [holderA, holderB] : [holderB, holderA];
  const h = crypto.createHash("sha256");
  h.update(Buffer.from("ct-link-channel-v1", "utf8"));
  h.update(operatorPubkey);
  h.update(lo);
  h.update(hi);
  return h.digest();
}

/** member_noise_attest_bytes: the exact preimage a member's holder key signs to attest that it
 *  authorized `noisePubkey` as its Noise static key on `channel`. */
function memberNoiseAttestBytes(channel, holder, noisePubkey) {
  return preimage("ct-a2a-noise-attest-v1", channel, holder, noisePubkey);
}

function rawEd25519PublicKey(raw32) {
  return crypto.createPublicKey({
    key: Buffer.concat([ED25519_SPKI_DER_PREFIX, raw32]),
    format: "der",
    type: "spki",
  });
}

/** verify_member_noise_attestation: `signature` must be `holder`'s ed25519 signature over
 *  memberNoiseAttestBytes(channel, holder, noisePubkey). Never throws — a malformed key or
 *  signature is just an invalid attestation, not an exception a caller has to guard against. */
function verifyMemberNoiseAttestation(channel, holder, noisePubkey, signature) {
  if (
    !Buffer.isBuffer(channel) || channel.length !== 32 ||
    !Buffer.isBuffer(holder) || holder.length !== 32 ||
    !Buffer.isBuffer(noisePubkey) || noisePubkey.length !== 32 ||
    !Buffer.isBuffer(signature) || signature.length !== 64
  ) {
    return false;
  }
  let keyObj;
  try {
    keyObj = rawEd25519PublicKey(holder);
  } catch {
    return false;
  }
  try {
    return crypto.verify(null, memberNoiseAttestBytes(channel, holder, noisePubkey), keyObj, signature);
  } catch {
    return false;
  }
}

module.exports = {
  channelIdForLink,
  memberNoiseAttestBytes,
  verifyMemberNoiseAttestation,
};
